/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  RunScriptResult,
  DeployContractExecutionResult,
  NetworkId,
} from "@alephium/web3";
import {
  ALPHUSDTOracle,
  ALPHUSDTOracleInstance,
  WBTCUSDTOracle,
  WBTCUSDTOracleInstance,
  LinxDiaOracle,
  LinxDiaOracleInstance,
  AlphUsdtOracle,
  AlphUsdtOracleInstance,
  WBTCETHOracle,
  WBTCETHOracleInstance,
  USDCUSDTOracle,
  USDCUSDTOracleInstance,
  DIAOracleWrapper,
  DIAOracleWrapperInstance,
} from ".";
import { default as mainnetDeployments } from "../../deployments/.deployments.mainnet.json";
import { default as testnetDeployments } from "../../deployments/.deployments.testnet.json";
import { default as devnetDeployments } from "../../deployments/.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    ALPHUSDTOracle?: DeployContractExecutionResult<ALPHUSDTOracleInstance>;
    WBTCUSDTOracle?: DeployContractExecutionResult<WBTCUSDTOracleInstance>;
    LinxDiaOracle?: DeployContractExecutionResult<LinxDiaOracleInstance>;
    AlphUsdtOracle?: DeployContractExecutionResult<AlphUsdtOracleInstance>;
    WBTCETHOracle?: DeployContractExecutionResult<WBTCETHOracleInstance>;
    USDCUSDTOracle?: DeployContractExecutionResult<USDCUSDTOracleInstance>;
    DIAOracleWrapper?: DeployContractExecutionResult<DIAOracleWrapperInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    ALPHUSDTOracle:
      json.contracts["ALPHUSDTOracle"] === undefined
        ? undefined
        : {
            ...json.contracts["ALPHUSDTOracle"],
            contractInstance: ALPHUSDTOracle.at(
              json.contracts["ALPHUSDTOracle"].contractInstance.address
            ),
          },
    WBTCUSDTOracle:
      json.contracts["WBTCUSDTOracle"] === undefined
        ? undefined
        : {
            ...json.contracts["WBTCUSDTOracle"],
            contractInstance: WBTCUSDTOracle.at(
              json.contracts["WBTCUSDTOracle"].contractInstance.address
            ),
          },
    LinxDiaOracle:
      json.contracts["LinxDiaOracle"] === undefined
        ? undefined
        : {
            ...json.contracts["LinxDiaOracle"],
            contractInstance: LinxDiaOracle.at(
              json.contracts["LinxDiaOracle"].contractInstance.address
            ),
          },
    AlphUsdtOracle:
      json.contracts["AlphUsdtOracle"] === undefined
        ? undefined
        : {
            ...json.contracts["AlphUsdtOracle"],
            contractInstance: AlphUsdtOracle.at(
              json.contracts["AlphUsdtOracle"].contractInstance.address
            ),
          },
    WBTCETHOracle:
      json.contracts["WBTCETHOracle"] === undefined
        ? undefined
        : {
            ...json.contracts["WBTCETHOracle"],
            contractInstance: WBTCETHOracle.at(
              json.contracts["WBTCETHOracle"].contractInstance.address
            ),
          },
    USDCUSDTOracle:
      json.contracts["USDCUSDTOracle"] === undefined
        ? undefined
        : {
            ...json.contracts["USDCUSDTOracle"],
            contractInstance: USDCUSDTOracle.at(
              json.contracts["USDCUSDTOracle"].contractInstance.address
            ),
          },
    DIAOracleWrapper:
      json.contracts["DIAOracleWrapper"] === undefined
        ? undefined
        : {
            ...json.contracts["DIAOracleWrapper"],
            contractInstance: DIAOracleWrapper.at(
              json.contracts["DIAOracleWrapper"].contractInstance.address
            ),
          },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments =
    networkId === "mainnet"
      ? mainnetDeployments
      : networkId === "testnet"
      ? testnetDeployments
      : networkId === "devnet"
      ? devnetDeployments
      : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments: any[] = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
