/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as DIAOracleWrapperContractJson } from "../DIAOracleWrapper.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import { DIAOracleValue, AllStructs } from "./types";

// Custom types for the contract
export namespace DIAOracleWrapperTypes {
  export type Fields = {
    diaOracleAddress: Address;
    marketId: HexString;
    heartbeatInterval: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    price: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    price: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  DIAOracleWrapperInstance,
  DIAOracleWrapperTypes.Fields
> {
  encodeFields(fields: DIAOracleWrapperTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  consts = { PRECISION: BigInt("24"), ErrorCodes: { StalePrice: BigInt("0") } };

  at(address: string): DIAOracleWrapperInstance {
    return new DIAOracleWrapperInstance(address);
  }

  tests = {
    price: async (
      params: Omit<
        TestContractParamsWithoutMaps<DIAOracleWrapperTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "price", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: DIAOracleWrapperTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const DIAOracleWrapper = new Factory(
  Contract.fromJson(
    DIAOracleWrapperContractJson,
    "",
    "e0e94814954464a641c01c396a1a58c8604aff3170fdd7149fc5ac7436ef7cd0",
    AllStructs
  )
);
registerContract(DIAOracleWrapper);

// Use this class to interact with the blockchain
export class DIAOracleWrapperInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DIAOracleWrapperTypes.State> {
    return fetchContractState(DIAOracleWrapper, this);
  }

  view = {
    price: async (
      params?: DIAOracleWrapperTypes.CallMethodParams<"price">
    ): Promise<DIAOracleWrapperTypes.CallMethodResult<"price">> => {
      return callMethod(
        DIAOracleWrapper,
        this,
        "price",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    price: async (
      params: DIAOracleWrapperTypes.SignExecuteMethodParams<"price">
    ): Promise<DIAOracleWrapperTypes.SignExecuteMethodResult<"price">> => {
      return signExecuteMethod(DIAOracleWrapper, this, "price", params);
    },
  };

  async multicall<Calls extends DIAOracleWrapperTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DIAOracleWrapperTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends DIAOracleWrapperTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<DIAOracleWrapperTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | DIAOracleWrapperTypes.MultiCallParams
      | DIAOracleWrapperTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      DIAOracleWrapper,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
