/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FixedIrmMockContractJson } from "../lib/linx-lending-core/contracts/test/FixedIrmMock.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import {
  DIAOracleValue,
  MarketParams,
  MarketState,
  Position,
  AllStructs,
} from "./types";

// Custom types for the contract
export namespace FixedIrmMockTypes {
  export type Fields = {
    rate: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    initInterest: {
      params: CallContractParams<{
        marketParams: MarketParams;
        marketState: MarketState;
      }>;
      result: CallContractResult<bigint>;
    };
    borrowRate: {
      params: CallContractParams<{
        marketParams: MarketParams;
        marketState: MarketState;
      }>;
      result: CallContractResult<bigint>;
    };
    getRate: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    setBorrowRate: {
      params: CallContractParams<{ newRate: bigint }>;
      result: CallContractResult<null>;
    };
    wMulDown: {
      params: CallContractParams<{ x: bigint; y: bigint }>;
      result: CallContractResult<bigint>;
    };
    wDivDown: {
      params: CallContractParams<{ x: bigint; y: bigint }>;
      result: CallContractResult<bigint>;
    };
    wDivUp: {
      params: CallContractParams<{ x: bigint; y: bigint }>;
      result: CallContractResult<bigint>;
    };
    mulDivDown: {
      params: CallContractParams<{ x: bigint; y: bigint; d: bigint }>;
      result: CallContractResult<bigint>;
    };
    mulDivUp: {
      params: CallContractParams<{ x: bigint; y: bigint; d: bigint }>;
      result: CallContractResult<bigint>;
    };
    wTaylorCompounded: {
      params: CallContractParams<{ x: bigint; n: bigint }>;
      result: CallContractResult<bigint>;
    };
    exactlyOneZero: {
      params: CallContractParams<{ a: bigint; b: bigint }>;
      result: CallContractResult<boolean>;
    };
    zeroFloorSub: {
      params: CallContractParams<{ x: bigint; y: bigint }>;
      result: CallContractResult<bigint>;
    };
    min: {
      params: CallContractParams<{ a: bigint; b: bigint }>;
      result: CallContractResult<bigint>;
    };
    toBaseUnits: {
      params: CallContractParams<{ amount: bigint; tokenDecimals: bigint }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    initInterest: {
      params: SignExecuteContractMethodParams<{
        marketParams: MarketParams;
        marketState: MarketState;
      }>;
      result: SignExecuteScriptTxResult;
    };
    borrowRate: {
      params: SignExecuteContractMethodParams<{
        marketParams: MarketParams;
        marketState: MarketState;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getRate: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setBorrowRate: {
      params: SignExecuteContractMethodParams<{ newRate: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    wMulDown: {
      params: SignExecuteContractMethodParams<{ x: bigint; y: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    wDivDown: {
      params: SignExecuteContractMethodParams<{ x: bigint; y: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    wDivUp: {
      params: SignExecuteContractMethodParams<{ x: bigint; y: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    mulDivDown: {
      params: SignExecuteContractMethodParams<{
        x: bigint;
        y: bigint;
        d: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mulDivUp: {
      params: SignExecuteContractMethodParams<{
        x: bigint;
        y: bigint;
        d: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    wTaylorCompounded: {
      params: SignExecuteContractMethodParams<{ x: bigint; n: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    exactlyOneZero: {
      params: SignExecuteContractMethodParams<{ a: bigint; b: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    zeroFloorSub: {
      params: SignExecuteContractMethodParams<{ x: bigint; y: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    min: {
      params: SignExecuteContractMethodParams<{ a: bigint; b: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    toBaseUnits: {
      params: SignExecuteContractMethodParams<{
        amount: bigint;
        tokenDecimals: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FixedIrmMockInstance,
  FixedIrmMockTypes.Fields
> {
  encodeFields(fields: FixedIrmMockTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  consts = { WAD: BigInt("1000000000000000000") };

  at(address: string): FixedIrmMockInstance {
    return new FixedIrmMockInstance(address);
  }

  tests = {
    initInterest: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { marketParams: MarketParams; marketState: MarketState }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "initInterest", params, getContractByCodeHash);
    },
    borrowRate: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { marketParams: MarketParams; marketState: MarketState }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "borrowRate", params, getContractByCodeHash);
    },
    getRate: async (
      params: Omit<
        TestContractParamsWithoutMaps<FixedIrmMockTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getRate", params, getContractByCodeHash);
    },
    setBorrowRate: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { newRate: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setBorrowRate", params, getContractByCodeHash);
    },
    wMulDown: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { x: bigint; y: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "wMulDown", params, getContractByCodeHash);
    },
    wDivDown: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { x: bigint; y: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "wDivDown", params, getContractByCodeHash);
    },
    wDivUp: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { x: bigint; y: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "wDivUp", params, getContractByCodeHash);
    },
    mulDivDown: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { x: bigint; y: bigint; d: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "mulDivDown", params, getContractByCodeHash);
    },
    mulDivUp: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { x: bigint; y: bigint; d: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "mulDivUp", params, getContractByCodeHash);
    },
    wTaylorCompounded: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { x: bigint; n: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "wTaylorCompounded",
        params,
        getContractByCodeHash
      );
    },
    exactlyOneZero: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { a: bigint; b: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "exactlyOneZero", params, getContractByCodeHash);
    },
    zeroFloorSub: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { x: bigint; y: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "zeroFloorSub", params, getContractByCodeHash);
    },
    min: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { a: bigint; b: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "min", params, getContractByCodeHash);
    },
    toBaseUnits: async (
      params: TestContractParamsWithoutMaps<
        FixedIrmMockTypes.Fields,
        { amount: bigint; tokenDecimals: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "toBaseUnits", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FixedIrmMockTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FixedIrmMock = new Factory(
  Contract.fromJson(
    FixedIrmMockContractJson,
    "",
    "6505d5245cc9b93901b4dcc784db82dd96eb80c245071149af2183d75e9ce91c",
    AllStructs
  )
);
registerContract(FixedIrmMock);

// Use this class to interact with the blockchain
export class FixedIrmMockInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FixedIrmMockTypes.State> {
    return fetchContractState(FixedIrmMock, this);
  }

  view = {
    initInterest: async (
      params: FixedIrmMockTypes.CallMethodParams<"initInterest">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"initInterest">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "initInterest",
        params,
        getContractByCodeHash
      );
    },
    borrowRate: async (
      params: FixedIrmMockTypes.CallMethodParams<"borrowRate">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"borrowRate">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "borrowRate",
        params,
        getContractByCodeHash
      );
    },
    getRate: async (
      params?: FixedIrmMockTypes.CallMethodParams<"getRate">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"getRate">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "getRate",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setBorrowRate: async (
      params: FixedIrmMockTypes.CallMethodParams<"setBorrowRate">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"setBorrowRate">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "setBorrowRate",
        params,
        getContractByCodeHash
      );
    },
    wMulDown: async (
      params: FixedIrmMockTypes.CallMethodParams<"wMulDown">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"wMulDown">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "wMulDown",
        params,
        getContractByCodeHash
      );
    },
    wDivDown: async (
      params: FixedIrmMockTypes.CallMethodParams<"wDivDown">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"wDivDown">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "wDivDown",
        params,
        getContractByCodeHash
      );
    },
    wDivUp: async (
      params: FixedIrmMockTypes.CallMethodParams<"wDivUp">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"wDivUp">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "wDivUp",
        params,
        getContractByCodeHash
      );
    },
    mulDivDown: async (
      params: FixedIrmMockTypes.CallMethodParams<"mulDivDown">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"mulDivDown">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "mulDivDown",
        params,
        getContractByCodeHash
      );
    },
    mulDivUp: async (
      params: FixedIrmMockTypes.CallMethodParams<"mulDivUp">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"mulDivUp">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "mulDivUp",
        params,
        getContractByCodeHash
      );
    },
    wTaylorCompounded: async (
      params: FixedIrmMockTypes.CallMethodParams<"wTaylorCompounded">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"wTaylorCompounded">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "wTaylorCompounded",
        params,
        getContractByCodeHash
      );
    },
    exactlyOneZero: async (
      params: FixedIrmMockTypes.CallMethodParams<"exactlyOneZero">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"exactlyOneZero">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "exactlyOneZero",
        params,
        getContractByCodeHash
      );
    },
    zeroFloorSub: async (
      params: FixedIrmMockTypes.CallMethodParams<"zeroFloorSub">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"zeroFloorSub">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "zeroFloorSub",
        params,
        getContractByCodeHash
      );
    },
    min: async (
      params: FixedIrmMockTypes.CallMethodParams<"min">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"min">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "min",
        params,
        getContractByCodeHash
      );
    },
    toBaseUnits: async (
      params: FixedIrmMockTypes.CallMethodParams<"toBaseUnits">
    ): Promise<FixedIrmMockTypes.CallMethodResult<"toBaseUnits">> => {
      return callMethod(
        FixedIrmMock,
        this,
        "toBaseUnits",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    initInterest: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"initInterest">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"initInterest">> => {
      return signExecuteMethod(FixedIrmMock, this, "initInterest", params);
    },
    borrowRate: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"borrowRate">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"borrowRate">> => {
      return signExecuteMethod(FixedIrmMock, this, "borrowRate", params);
    },
    getRate: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"getRate">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"getRate">> => {
      return signExecuteMethod(FixedIrmMock, this, "getRate", params);
    },
    setBorrowRate: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"setBorrowRate">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"setBorrowRate">> => {
      return signExecuteMethod(FixedIrmMock, this, "setBorrowRate", params);
    },
    wMulDown: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"wMulDown">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"wMulDown">> => {
      return signExecuteMethod(FixedIrmMock, this, "wMulDown", params);
    },
    wDivDown: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"wDivDown">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"wDivDown">> => {
      return signExecuteMethod(FixedIrmMock, this, "wDivDown", params);
    },
    wDivUp: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"wDivUp">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"wDivUp">> => {
      return signExecuteMethod(FixedIrmMock, this, "wDivUp", params);
    },
    mulDivDown: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"mulDivDown">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"mulDivDown">> => {
      return signExecuteMethod(FixedIrmMock, this, "mulDivDown", params);
    },
    mulDivUp: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"mulDivUp">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"mulDivUp">> => {
      return signExecuteMethod(FixedIrmMock, this, "mulDivUp", params);
    },
    wTaylorCompounded: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"wTaylorCompounded">
    ): Promise<
      FixedIrmMockTypes.SignExecuteMethodResult<"wTaylorCompounded">
    > => {
      return signExecuteMethod(FixedIrmMock, this, "wTaylorCompounded", params);
    },
    exactlyOneZero: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"exactlyOneZero">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"exactlyOneZero">> => {
      return signExecuteMethod(FixedIrmMock, this, "exactlyOneZero", params);
    },
    zeroFloorSub: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"zeroFloorSub">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"zeroFloorSub">> => {
      return signExecuteMethod(FixedIrmMock, this, "zeroFloorSub", params);
    },
    min: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"min">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"min">> => {
      return signExecuteMethod(FixedIrmMock, this, "min", params);
    },
    toBaseUnits: async (
      params: FixedIrmMockTypes.SignExecuteMethodParams<"toBaseUnits">
    ): Promise<FixedIrmMockTypes.SignExecuteMethodResult<"toBaseUnits">> => {
      return signExecuteMethod(FixedIrmMock, this, "toBaseUnits", params);
    },
  };

  async multicall<Calls extends FixedIrmMockTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FixedIrmMockTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends FixedIrmMockTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FixedIrmMockTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | FixedIrmMockTypes.MultiCallParams
      | FixedIrmMockTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      FixedIrmMock,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
