/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FungibleTokenContractJson } from "../lib/linx-ralph-libs/contracts/test/FungibleToken.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import {
  DIAOracleValue,
  MarketParams,
  MarketState,
  Position,
  AllStructs,
} from "./types";

// Custom types for the contract
export namespace FungibleTokenTypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
    decimals: bigint;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getToken: {
      params: CallContractParams<{ sender: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getToken: {
      params: SignExecuteContractMethodParams<{
        sender: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FungibleTokenInstance,
  FungibleTokenTypes.Fields
> {
  encodeFields(fields: FungibleTokenTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): FungibleTokenInstance {
    return new FungibleTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<FungibleTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<FungibleTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<FungibleTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<FungibleTokenTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    getToken: async (
      params: TestContractParamsWithoutMaps<
        FungibleTokenTypes.Fields,
        { sender: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "getToken", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FungibleTokenTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FungibleToken = new Factory(
  Contract.fromJson(
    FungibleTokenContractJson,
    "",
    "f9dac4e7d0bf28a2bc019f43138339e23afadde322d50441cdfe029993bf35f3",
    AllStructs
  )
);
registerContract(FungibleToken);

// Use this class to interact with the blockchain
export class FungibleTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FungibleTokenTypes.State> {
    return fetchContractState(FungibleToken, this);
  }

  view = {
    getSymbol: async (
      params?: FungibleTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<FungibleTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        FungibleToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: FungibleTokenTypes.CallMethodParams<"getName">
    ): Promise<FungibleTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        FungibleToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: FungibleTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<FungibleTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        FungibleToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: FungibleTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<FungibleTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        FungibleToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getToken: async (
      params: FungibleTokenTypes.CallMethodParams<"getToken">
    ): Promise<FungibleTokenTypes.CallMethodResult<"getToken">> => {
      return callMethod(
        FungibleToken,
        this,
        "getToken",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: FungibleTokenTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<FungibleTokenTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(FungibleToken, this, "getSymbol", params);
    },
    getName: async (
      params: FungibleTokenTypes.SignExecuteMethodParams<"getName">
    ): Promise<FungibleTokenTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(FungibleToken, this, "getName", params);
    },
    getDecimals: async (
      params: FungibleTokenTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<FungibleTokenTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(FungibleToken, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: FungibleTokenTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<
      FungibleTokenTypes.SignExecuteMethodResult<"getTotalSupply">
    > => {
      return signExecuteMethod(FungibleToken, this, "getTotalSupply", params);
    },
    getToken: async (
      params: FungibleTokenTypes.SignExecuteMethodParams<"getToken">
    ): Promise<FungibleTokenTypes.SignExecuteMethodResult<"getToken">> => {
      return signExecuteMethod(FungibleToken, this, "getToken", params);
    },
  };

  async multicall<Calls extends FungibleTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FungibleTokenTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends FungibleTokenTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FungibleTokenTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | FungibleTokenTypes.MultiCallParams
      | FungibleTokenTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      FungibleToken,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
