/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as OracleMockContractJson } from "../lib/linx-lending-core/contracts/test/OracleMock.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import {
  DIAOracleValue,
  MarketParams,
  MarketState,
  Position,
  AllStructs,
} from "./types";

// Custom types for the contract
export namespace OracleMockTypes {
  export type Fields = {
    price: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    price: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    setPrice: {
      params: CallContractParams<{ newPrice: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    price: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setPrice: {
      params: SignExecuteContractMethodParams<{ newPrice: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  OracleMockInstance,
  OracleMockTypes.Fields
> {
  encodeFields(fields: OracleMockTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  at(address: string): OracleMockInstance {
    return new OracleMockInstance(address);
  }

  tests = {
    price: async (
      params: Omit<
        TestContractParamsWithoutMaps<OracleMockTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "price", params, getContractByCodeHash);
    },
    setPrice: async (
      params: TestContractParamsWithoutMaps<
        OracleMockTypes.Fields,
        { newPrice: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setPrice", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: OracleMockTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const OracleMock = new Factory(
  Contract.fromJson(
    OracleMockContractJson,
    "",
    "63880767e7aab740e59a6166622cac29d502da75fa87f74ebc9fcf49f46252d8",
    AllStructs
  )
);
registerContract(OracleMock);

// Use this class to interact with the blockchain
export class OracleMockInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<OracleMockTypes.State> {
    return fetchContractState(OracleMock, this);
  }

  view = {
    price: async (
      params?: OracleMockTypes.CallMethodParams<"price">
    ): Promise<OracleMockTypes.CallMethodResult<"price">> => {
      return callMethod(
        OracleMock,
        this,
        "price",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setPrice: async (
      params: OracleMockTypes.CallMethodParams<"setPrice">
    ): Promise<OracleMockTypes.CallMethodResult<"setPrice">> => {
      return callMethod(
        OracleMock,
        this,
        "setPrice",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    price: async (
      params: OracleMockTypes.SignExecuteMethodParams<"price">
    ): Promise<OracleMockTypes.SignExecuteMethodResult<"price">> => {
      return signExecuteMethod(OracleMock, this, "price", params);
    },
    setPrice: async (
      params: OracleMockTypes.SignExecuteMethodParams<"setPrice">
    ): Promise<OracleMockTypes.SignExecuteMethodResult<"setPrice">> => {
      return signExecuteMethod(OracleMock, this, "setPrice", params);
    },
  };

  async multicall<Calls extends OracleMockTypes.MultiCallParams>(
    calls: Calls
  ): Promise<OracleMockTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends OracleMockTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<OracleMockTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | OracleMockTypes.MultiCallParams
      | OracleMockTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      OracleMock,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
