/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as OracleMockContractJson } from "../lib/linx-lending-core/contracts/test/OracleMock.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import {
  DIAOracleValue,
  MarketParams,
  MarketState,
  Position,
  AllStructs,
} from "./types";

// Custom types for the contract
export namespace OracleMockTypes {
  export type State = Omit<ContractState<any>, "fields">;

  export interface CallMethodTable {
    price: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    price: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<OracleMockInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, AllStructs);
  }

  at(address: string): OracleMockInstance {
    return new OracleMockInstance(address);
  }

  tests = {
    price: async (
      params?: Omit<
        TestContractParamsWithoutMaps<never, never>,
        "args" | "initialFields"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "price",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const OracleMock = new Factory(
  Contract.fromJson(
    OracleMockContractJson,
    "",
    "129659a654ca07b1f400f291b61c5a0112d6e0536920c8f4654d2c74679954d8",
    AllStructs
  )
);
registerContract(OracleMock);

// Use this class to interact with the blockchain
export class OracleMockInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<OracleMockTypes.State> {
    return fetchContractState(OracleMock, this);
  }

  view = {
    price: async (
      params?: OracleMockTypes.CallMethodParams<"price">
    ): Promise<OracleMockTypes.CallMethodResult<"price">> => {
      return callMethod(
        OracleMock,
        this,
        "price",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    price: async (
      params: OracleMockTypes.SignExecuteMethodParams<"price">
    ): Promise<OracleMockTypes.SignExecuteMethodResult<"price">> => {
      return signExecuteMethod(OracleMock, this, "price", params);
    },
  };

  async multicall<Calls extends OracleMockTypes.MultiCallParams>(
    calls: Calls
  ): Promise<OracleMockTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends OracleMockTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<OracleMockTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | OracleMockTypes.MultiCallParams
      | OracleMockTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      OracleMock,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
