/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as CreateMarketAndAccrueInterestScriptJson } from "../lib/linx-lending-core/contracts/test/CreateMarketAndAccrueInterest.ral.json";
import {
  DIAOracleValue,
  MarketParams,
  MarketState,
  Position,
  AllStructs,
} from "./types";

export const CreateMarketAndAccrueInterest = new ExecutableScript<{
  linx: HexString;
  params: MarketParams;
}>(
  Script.fromJson(CreateMarketAndAccrueInterestScriptJson, "", AllStructs),
  getContractByCodeHash
);
