/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as WBTCETHOracleContractJson } from "../oracles/WBTCETHOracle.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import {
  DIAOracleValue,
  MarketParams,
  MarketState,
  Position,
  AllStructs,
} from "./types";

// Custom types for the contract
export namespace WBTCETHOracleTypes {
  export type Fields = {
    diaOracleContractId: HexString;
    baseMarketId: HexString;
    quoteMarketId: HexString;
    baseMarketDecimals: bigint;
    quoteMarketDecimals: bigint;
    baseTokenDecimals: bigint;
    quoteTokenDecimals: bigint;
    heartbeatInterval: bigint;
    scaleFactor: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    price: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    init: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    wMulDown: {
      params: CallContractParams<{ x: bigint; y: bigint }>;
      result: CallContractResult<bigint>;
    };
    wDivDown: {
      params: CallContractParams<{ x: bigint; y: bigint }>;
      result: CallContractResult<bigint>;
    };
    wDivUp: {
      params: CallContractParams<{ x: bigint; y: bigint }>;
      result: CallContractResult<bigint>;
    };
    mulDivDown: {
      params: CallContractParams<{ x: bigint; y: bigint; d: bigint }>;
      result: CallContractResult<bigint>;
    };
    mulDivUp: {
      params: CallContractParams<{ x: bigint; y: bigint; d: bigint }>;
      result: CallContractResult<bigint>;
    };
    wTaylorCompounded: {
      params: CallContractParams<{ x: bigint; n: bigint }>;
      result: CallContractResult<bigint>;
    };
    exactlyOneZero: {
      params: CallContractParams<{ a: bigint; b: bigint }>;
      result: CallContractResult<boolean>;
    };
    zeroFloorSub: {
      params: CallContractParams<{ x: bigint; y: bigint }>;
      result: CallContractResult<bigint>;
    };
    min: {
      params: CallContractParams<{ a: bigint; b: bigint }>;
      result: CallContractResult<bigint>;
    };
    toBaseUnits: {
      params: CallContractParams<{ amount: bigint; tokenDecimals: bigint }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    price: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    init: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    wMulDown: {
      params: SignExecuteContractMethodParams<{ x: bigint; y: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    wDivDown: {
      params: SignExecuteContractMethodParams<{ x: bigint; y: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    wDivUp: {
      params: SignExecuteContractMethodParams<{ x: bigint; y: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    mulDivDown: {
      params: SignExecuteContractMethodParams<{
        x: bigint;
        y: bigint;
        d: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mulDivUp: {
      params: SignExecuteContractMethodParams<{
        x: bigint;
        y: bigint;
        d: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    wTaylorCompounded: {
      params: SignExecuteContractMethodParams<{ x: bigint; n: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    exactlyOneZero: {
      params: SignExecuteContractMethodParams<{ a: bigint; b: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    zeroFloorSub: {
      params: SignExecuteContractMethodParams<{ x: bigint; y: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    min: {
      params: SignExecuteContractMethodParams<{ a: bigint; b: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    toBaseUnits: {
      params: SignExecuteContractMethodParams<{
        amount: bigint;
        tokenDecimals: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  WBTCETHOracleInstance,
  WBTCETHOracleTypes.Fields
> {
  encodeFields(fields: WBTCETHOracleTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  consts = {
    WAD: BigInt("1000000000000000000"),
    ErrorCodes: { StalePrice: BigInt("0"), NotInitialized: BigInt("1") },
  };

  at(address: string): WBTCETHOracleInstance {
    return new WBTCETHOracleInstance(address);
  }

  tests = {
    price: async (
      params: Omit<
        TestContractParamsWithoutMaps<WBTCETHOracleTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "price", params, getContractByCodeHash);
    },
    init: async (
      params: Omit<
        TestContractParamsWithoutMaps<WBTCETHOracleTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "init", params, getContractByCodeHash);
    },
    wMulDown: async (
      params: TestContractParamsWithoutMaps<
        WBTCETHOracleTypes.Fields,
        { x: bigint; y: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "wMulDown", params, getContractByCodeHash);
    },
    wDivDown: async (
      params: TestContractParamsWithoutMaps<
        WBTCETHOracleTypes.Fields,
        { x: bigint; y: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "wDivDown", params, getContractByCodeHash);
    },
    wDivUp: async (
      params: TestContractParamsWithoutMaps<
        WBTCETHOracleTypes.Fields,
        { x: bigint; y: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "wDivUp", params, getContractByCodeHash);
    },
    mulDivDown: async (
      params: TestContractParamsWithoutMaps<
        WBTCETHOracleTypes.Fields,
        { x: bigint; y: bigint; d: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "mulDivDown", params, getContractByCodeHash);
    },
    mulDivUp: async (
      params: TestContractParamsWithoutMaps<
        WBTCETHOracleTypes.Fields,
        { x: bigint; y: bigint; d: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "mulDivUp", params, getContractByCodeHash);
    },
    wTaylorCompounded: async (
      params: TestContractParamsWithoutMaps<
        WBTCETHOracleTypes.Fields,
        { x: bigint; n: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "wTaylorCompounded",
        params,
        getContractByCodeHash
      );
    },
    exactlyOneZero: async (
      params: TestContractParamsWithoutMaps<
        WBTCETHOracleTypes.Fields,
        { a: bigint; b: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "exactlyOneZero", params, getContractByCodeHash);
    },
    zeroFloorSub: async (
      params: TestContractParamsWithoutMaps<
        WBTCETHOracleTypes.Fields,
        { x: bigint; y: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "zeroFloorSub", params, getContractByCodeHash);
    },
    min: async (
      params: TestContractParamsWithoutMaps<
        WBTCETHOracleTypes.Fields,
        { a: bigint; b: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "min", params, getContractByCodeHash);
    },
    toBaseUnits: async (
      params: TestContractParamsWithoutMaps<
        WBTCETHOracleTypes.Fields,
        { amount: bigint; tokenDecimals: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "toBaseUnits", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: WBTCETHOracleTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const WBTCETHOracle = new Factory(
  Contract.fromJson(
    WBTCETHOracleContractJson,
    "",
    "8a3eb1223b39d37b94435a8d0cddcf757eb5c62cbefa726a0c4a14752ea0d3ff",
    AllStructs
  )
);
registerContract(WBTCETHOracle);

// Use this class to interact with the blockchain
export class WBTCETHOracleInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<WBTCETHOracleTypes.State> {
    return fetchContractState(WBTCETHOracle, this);
  }

  view = {
    price: async (
      params?: WBTCETHOracleTypes.CallMethodParams<"price">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"price">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "price",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    init: async (
      params?: WBTCETHOracleTypes.CallMethodParams<"init">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"init">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "init",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    wMulDown: async (
      params: WBTCETHOracleTypes.CallMethodParams<"wMulDown">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"wMulDown">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "wMulDown",
        params,
        getContractByCodeHash
      );
    },
    wDivDown: async (
      params: WBTCETHOracleTypes.CallMethodParams<"wDivDown">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"wDivDown">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "wDivDown",
        params,
        getContractByCodeHash
      );
    },
    wDivUp: async (
      params: WBTCETHOracleTypes.CallMethodParams<"wDivUp">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"wDivUp">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "wDivUp",
        params,
        getContractByCodeHash
      );
    },
    mulDivDown: async (
      params: WBTCETHOracleTypes.CallMethodParams<"mulDivDown">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"mulDivDown">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "mulDivDown",
        params,
        getContractByCodeHash
      );
    },
    mulDivUp: async (
      params: WBTCETHOracleTypes.CallMethodParams<"mulDivUp">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"mulDivUp">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "mulDivUp",
        params,
        getContractByCodeHash
      );
    },
    wTaylorCompounded: async (
      params: WBTCETHOracleTypes.CallMethodParams<"wTaylorCompounded">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"wTaylorCompounded">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "wTaylorCompounded",
        params,
        getContractByCodeHash
      );
    },
    exactlyOneZero: async (
      params: WBTCETHOracleTypes.CallMethodParams<"exactlyOneZero">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"exactlyOneZero">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "exactlyOneZero",
        params,
        getContractByCodeHash
      );
    },
    zeroFloorSub: async (
      params: WBTCETHOracleTypes.CallMethodParams<"zeroFloorSub">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"zeroFloorSub">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "zeroFloorSub",
        params,
        getContractByCodeHash
      );
    },
    min: async (
      params: WBTCETHOracleTypes.CallMethodParams<"min">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"min">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "min",
        params,
        getContractByCodeHash
      );
    },
    toBaseUnits: async (
      params: WBTCETHOracleTypes.CallMethodParams<"toBaseUnits">
    ): Promise<WBTCETHOracleTypes.CallMethodResult<"toBaseUnits">> => {
      return callMethod(
        WBTCETHOracle,
        this,
        "toBaseUnits",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    price: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"price">
    ): Promise<WBTCETHOracleTypes.SignExecuteMethodResult<"price">> => {
      return signExecuteMethod(WBTCETHOracle, this, "price", params);
    },
    init: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"init">
    ): Promise<WBTCETHOracleTypes.SignExecuteMethodResult<"init">> => {
      return signExecuteMethod(WBTCETHOracle, this, "init", params);
    },
    wMulDown: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"wMulDown">
    ): Promise<WBTCETHOracleTypes.SignExecuteMethodResult<"wMulDown">> => {
      return signExecuteMethod(WBTCETHOracle, this, "wMulDown", params);
    },
    wDivDown: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"wDivDown">
    ): Promise<WBTCETHOracleTypes.SignExecuteMethodResult<"wDivDown">> => {
      return signExecuteMethod(WBTCETHOracle, this, "wDivDown", params);
    },
    wDivUp: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"wDivUp">
    ): Promise<WBTCETHOracleTypes.SignExecuteMethodResult<"wDivUp">> => {
      return signExecuteMethod(WBTCETHOracle, this, "wDivUp", params);
    },
    mulDivDown: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"mulDivDown">
    ): Promise<WBTCETHOracleTypes.SignExecuteMethodResult<"mulDivDown">> => {
      return signExecuteMethod(WBTCETHOracle, this, "mulDivDown", params);
    },
    mulDivUp: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"mulDivUp">
    ): Promise<WBTCETHOracleTypes.SignExecuteMethodResult<"mulDivUp">> => {
      return signExecuteMethod(WBTCETHOracle, this, "mulDivUp", params);
    },
    wTaylorCompounded: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"wTaylorCompounded">
    ): Promise<
      WBTCETHOracleTypes.SignExecuteMethodResult<"wTaylorCompounded">
    > => {
      return signExecuteMethod(
        WBTCETHOracle,
        this,
        "wTaylorCompounded",
        params
      );
    },
    exactlyOneZero: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"exactlyOneZero">
    ): Promise<
      WBTCETHOracleTypes.SignExecuteMethodResult<"exactlyOneZero">
    > => {
      return signExecuteMethod(WBTCETHOracle, this, "exactlyOneZero", params);
    },
    zeroFloorSub: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"zeroFloorSub">
    ): Promise<WBTCETHOracleTypes.SignExecuteMethodResult<"zeroFloorSub">> => {
      return signExecuteMethod(WBTCETHOracle, this, "zeroFloorSub", params);
    },
    min: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"min">
    ): Promise<WBTCETHOracleTypes.SignExecuteMethodResult<"min">> => {
      return signExecuteMethod(WBTCETHOracle, this, "min", params);
    },
    toBaseUnits: async (
      params: WBTCETHOracleTypes.SignExecuteMethodParams<"toBaseUnits">
    ): Promise<WBTCETHOracleTypes.SignExecuteMethodResult<"toBaseUnits">> => {
      return signExecuteMethod(WBTCETHOracle, this, "toBaseUnits", params);
    },
  };

  async multicall<Calls extends WBTCETHOracleTypes.MultiCallParams>(
    calls: Calls
  ): Promise<WBTCETHOracleTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends WBTCETHOracleTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<WBTCETHOracleTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | WBTCETHOracleTypes.MultiCallParams
      | WBTCETHOracleTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      WBTCETHOracle,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
