/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as GetBorrowRateScriptJson } from "../GetBorrowRate.ral.json";
import { default as GetBorrowRateAndUpdateScriptJson } from "../GetBorrowRateAndUpdate.ral.json";
import { default as GetMarketIdScriptJson } from "../GetMarketId.ral.json";
import { default as GetRateAtTargetScriptJson } from "../GetRateAtTarget.ral.json";
import { default as SetFixedRateScriptJson } from "../SetFixedRate.ral.json";
import { MarketParams, MarketState, AllStructs } from "./types";

export const GetBorrowRate = new ExecutableScript<
  {
    dynamicRate: HexString;
    marketParams: MarketParams;
    marketState: MarketState;
  },
  bigint
>(
  Script.fromJson(GetBorrowRateScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const GetBorrowRateAndUpdate = new ExecutableScript<
  {
    dynamicRate: HexString;
    marketParams: MarketParams;
    marketState: MarketState;
  },
  bigint
>(
  Script.fromJson(GetBorrowRateAndUpdateScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const GetMarketId = new ExecutableScript<
  { dynamicRate: HexString; loanToken: HexString; collateralToken: HexString },
  HexString
>(
  Script.fromJson(GetMarketIdScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const GetRateAtTarget = new ExecutableScript<
  { dynamicRate: HexString; loanToken: HexString; collateralToken: HexString },
  bigint
>(
  Script.fromJson(GetRateAtTargetScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const SetFixedRate = new ExecutableScript<{
  fixedRate: HexString;
  newBorrowRate: bigint;
}>(
  Script.fromJson(SetFixedRateScriptJson, "", AllStructs),
  getContractByCodeHash
);
