/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as GetBorrowRateScriptJson } from "../GetBorrowRate.ral.json";
import { default as GetBorrowRateAndUpdateScriptJson } from "../GetBorrowRateAndUpdate.ral.json";
import { default as GetContractCodeHashScriptJson } from "../GetContractCodeHash.ral.json";
import { default as SetFixedRateScriptJson } from "../SetFixedRate.ral.json";
import * as types from "./types";

export const GetBorrowRate = new ExecutableScript<
  {
    irm: HexString;
    marketParams: types.MarketParams;
    marketState: types.MarketState;
  },
  bigint
>(
  Script.fromJson(GetBorrowRateScriptJson, "", types.AllStructs),
  getContractByCodeHash
);

export const GetBorrowRateAndUpdate = new ExecutableScript<
  {
    dynamicRate: HexString;
    marketParams: types.MarketParams;
    marketState: types.MarketState;
  },
  bigint
>(
  Script.fromJson(GetBorrowRateAndUpdateScriptJson, "", types.AllStructs),
  getContractByCodeHash
);

export const GetContractCodeHash = new ExecutableScript<
  { contractId: HexString },
  HexString
>(
  Script.fromJson(GetContractCodeHashScriptJson, "", types.AllStructs),
  getContractByCodeHash
);

export const SetFixedRate = new ExecutableScript<{
  fixedRate: HexString;
  newBorrowRate: bigint;
}>(
  Script.fromJson(SetFixedRateScriptJson, "", types.AllStructs),
  getContractByCodeHash
);
