/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Address, HexString, Val, Struct } from "@alephium/web3";
import { default as allStructsJson } from "../structs.ral.json";
export const AllStructs = allStructsJson.map((json) => Struct.fromJson(json));
export interface MarketParams extends Record<string, Val> {
  loanToken: HexString;
  collateralToken: HexString;
  oracle: HexString;
  interestRateModel: HexString;
  loanToValue: bigint;
}
export interface MarketState extends Record<string, Val> {
  totalSupplyAssets: bigint;
  totalSupplyShares: bigint;
  totalBorrowAssets: bigint;
  totalBorrowShares: bigint;
  lastUpdate: bigint;
  fee: bigint;
}
